name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: secretroot
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        php: [ '8.2', '8.3' ]

    steps:
      -   name: Checkout
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            coverage: "none"
            php-version: ${{ matrix.php }}
            extensions: pdo, sqlite
            ini-file: development
            tools: composer:v2

      -   name: Install dependencies
          run: composer update --ansi --no-progress

      -   name: Run tests
          run: vendor/bin/pest
          env:
            DB_CONNECTION: mysql
            DB_HOST: 127.0.0.1
            DB_DATABASE: test
            DB_USERNAME: user
            DB_PASSWORD: secret
            DB_PORT: ${{ job.services.mysql.ports[3306] }}

  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            coverage: "none"
            php-version: "8.3"
            ini-file: development

      -   name: Install dependencies
          run: composer update --ansi --no-progress

      -   name: Run phpstan
          run: vendor/bin/phpstan analyse --ansi --no-progress